server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
